#* Title: Ex. 03 - Draw age to death from heterogeneous cohort
#* 
#* Code function: 
#*    This code corresponds to the third example of the NPS manuscript.
#*    
#*    It showcases a use of the nps_nhppp function while drawing
#*    ages to death from a heterogeneous cohort in 2015.
#*    
#*    The heterogeneous cohort is generated by disaggregating the population by the
#*    the "male" and "female" sexes.
#* 
#* Creation date: February 01 2024
#* Authors:
#* - David U. Garibay-Treviño, M.Sc.
#* - Hawre Jalal, M.D., Ph.D.
#* - Fernando Alarid-Escudero, Ph.D.

# 01 Initial Setup --------------------------------------------------------

## 01.01 Clean environment ------------------------------------------------
remove(list = ls())

#* Refresh environment memory
gc()

## 01.02 Load libraries ----------------------------------------------------
library(dplyr)
library(ggplot2)
library(tidyr)
library(tibble)
library(microbenchmark)

# Load function to implement multivariate categorical sampling
source(file = "R/nps_nhppp.R")


# 02 Define general parameters --------------------------------------------

# Number of samples to draw from the life table
n_samp_life_tables <- 1e5

# Number of samples, by sex, to draw from the life table
n_samp_by_sex <- 1e5

# Number of iterations for microbenchmarking
n_samp_iter_life_tables <- 100



# Seed for reproducibility in random number generation
n_seed <- 10242022

# To print a specific number of digits in tibbles
options(pillar.sigfig = 4)

# 03 Load base data -------------------------------------------------------

#' Yearly USA data, from 2000 to 2019, 
#' Mortality rate for males, females and total
#' Obtained from The Human Mortality Database:
#' https://www.mortality.org/cgi-bin/hmd/country.php?cntr=USA&level=1
load("data/all_cause_mortality.rda")


# 04 Filter data ----------------------------------------------------------

# For homogeneous population example
df_all_cause_mortality_filt <- all_cause_mortality %>% 
  as_tibble() %>% 
  filter(Year == 2015)

# 05 Data wrangling -------------------------------------------------------

#* Following Lee & Wang (2013) - Statistical methods for survival data analysis
#* 4th ed - chapter 2: Functions of survival time
df_lifetable <- df_all_cause_mortality_filt %>% 
  dplyr::arrange(Sex, Year, Age) %>% 
  dplyr::group_by(Sex) %>% 
  dplyr::mutate(
    H_t = cumsum(Rate),        # H(t) - Cumulative hazard
    S_t = exp(-H_t),           # S(t) - Cumulative survival
    F_t = 1 - exp(-H_t),       # F(t) - Cumulative probability: 1 - S(t)
    p_t = c(F_t[1], diff(F_t)) # f(t) - Instantaneous probability
  ) %>% 
  ungroup()


# Calculate life expectancy from lifetables data
df_le_lifetable <- df_lifetable %>% 
  group_by(Sex) %>% 
  summarise(le = sum(S_t))


# Obtain life expectancy by sex from life tables
le_lifetable_fem  <- df_le_lifetable[df_le_lifetable$Sex == "Female",]$le
le_lifetable_male <- df_le_lifetable[df_le_lifetable$Sex == "Male",]$le




# 06 Calculate life expectancy using nps method ---------------------------

v_samp_sex <- c("Male", "Female")

# Filter to have heterogeneous population
df_lifetable_heterog <- df_lifetable %>%
  filter(Sex != "Total") %>% 
  dplyr::select(Year, Sex, Age, p_t) %>% 
  # Normalize probabilities by sex
  group_by(Sex) %>% 
  # Normalize instantaneous probabilities by sex
  mutate(p_t = p_t / sum(p_t)) %>% 
  ungroup()

# Generate synthetic cohort with 50% males and 50% females
df_samp_raw <- tibble::tibble(
  Year = 2015,
  Sex = c(rep(x    = v_samp_sex, 
              each = n_samp_by_sex)))

# Convert lifetable data from long to wide
df_lifetable_probs_wide <- tidyr::pivot_wider(
  data = df_lifetable_heterog,
  names_from = Age,
  values_from = p_t,
  names_prefix = "Age_")

# Generate dataset for Multivariate categorical sampling
df_samp_probs <- df_samp_raw %>% 
  left_join(y = df_lifetable_probs_wide,
            by = join_by(Year, Sex))

#* Extract probability matrix from `df_samp_probs`
m_probs <- df_samp_probs %>% 
  dplyr::select(-Year, -Sex) %>% 
  as.matrix()

# Seed for reproducibility in random number generation
set.seed(n_seed)

#* Implement Multivariate NPS
##* Without continuous time approximation
v_cat_life_table_heterog <- nps_nhppp(m_probs = m_probs,
                                      correction = "none")

# Seed for reproducibility in random number generation
set.seed(n_seed)

##* With continuous time approximation
v_cat_life_table_heterog_corr <- nps_nhppp(m_probs = m_probs,
                                           correction = "uniform")

# Remove seed
set.seed(NULL)

# Create dataset with the age to death samples
df_heterog_samp <- df_samp_raw %>% 
  mutate(age_death      = v_cat_life_table_heterog,
         age_death_corr = v_cat_life_table_heterog_corr,
         .after = Sex)

#* Obtain life expectancies by sex
df_le_nps_heterog <- df_heterog_samp %>% 
  group_by(Sex) %>% 
  summarise(le = mean(age_death),
            le_corr = mean(age_death_corr)) %>% 
  ungroup()


# Extract values
le_nps_fem_uncorr  <- filter(df_le_nps_heterog, Sex == "Female")$le
le_nps_male_uncorr <- filter(df_le_nps_heterog, Sex == "Male")$le

le_nps_fem_corr   <- filter(df_le_nps_heterog, Sex == "Female")$le_corr
le_nps_male_corr   <- filter(df_le_nps_heterog, Sex == "Male")$le_corr


# Measure mean execution time
## Without continuous time correction
l_mbench_heterog_uncorr <- microbenchmark::microbenchmark(
  nps_nhppp(m_probs = m_probs, correction = "none"),
  times = n_samp_iter_life_tables,
  unit = "ms")

## With continuous time correction
l_mbench_heterog_corr <- microbenchmark::microbenchmark(
  nps_nhppp(m_probs = m_probs, correction = "uniform"),
  times = n_samp_iter_life_tables,
  unit = "ms")

# 07 Summarize results ----------------------------------------------------

# Create dataframe with summarized results
df_summary <- tibble::tibble(
  Source             = c("Life tables - females", "Life tables - males"),
  Exact              = c(le_lifetable_fem, le_lifetable_male),
  NPS                = c(le_nps_fem_uncorr, le_nps_male_uncorr),
  NPS_continous_time = c(le_nps_fem_corr, le_nps_male_corr))


# Check results table
df_summary



# 08 Plotting -------------------------------------------------------------

axis_text_size    <- 11
axis_title_size   <- 14
legend_text_size  <- 14
legend_title_size <- 14
title_size        <- 14

ggplt_lifetable_comparison_heterog <- ggplot(data = df_heterog_samp, 
                                             mapping = aes(x = age_death)) + 
  geom_histogram(mapping = aes(y = after_stat(density),
                               color = "Sample from NPS"),
                 binwidth = 1,
                 boundary = 0,
                 fill = NA,
                 closed = "left") + 
  geom_segment(data = df_lifetable_heterog,
               mapping = aes(x = Age, xend = Age + 1,
                             y = p_t, yend = p_t,
                             color = "Lifetables"),
               linewidth = 1) + 
  facet_wrap(facets = ~Sex,
             labeller = labeller(Sex = c("Female" = "Females", 
                                         "Male" = "Males"))) +
  scale_x_continuous(breaks       = seq(0, 100, by = 10),
                     minor_breaks = seq(0, 100, by = 5)) + 
  theme_bw() + 
  scale_color_manual(name = "Type",
                     values = c("Sample from NPS" = "salmon1",
                                "Lifetables" = "black")) + 
  labs(x = "Age of death",
       y = "Probability of death") +
  theme(legend.position = "bottom",
        axis.text     = element_text(size = axis_text_size),
        axis.title    = element_text(size = axis_title_size),
        legend.text   = element_text(size = legend_text_size),
        legend.title  = element_text(size = legend_title_size),
        plot.title    = element_text(size = title_size - 4, hjust = 0.5),
        plot.subtitle = element_text(size = title_size - 6, hjust = 0.5),
        plot.caption  = element_text(size = title_size - 8),
        strip.text    = element_text(size = axis_text_size, face = "bold"))

